# Generated by Django 4.0.3 on 2023-02-13 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='formaddmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=250, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Last Name')),
                ('PhoneNo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone No')),
                ('address', models.CharField(blank=True, max_length=1250, null=True, verbose_name='Address')),
                ('college', models.CharField(blank=True, max_length=1250, null=True, verbose_name='Required College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
