# Generated by Django 4.0.3 on 2023-02-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaddmision',
            name='user',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='user'),
        ),
    ]
