# Generated by Django 4.0.3 on 2023-02-09 12:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('BlogContent', ckeditor.fields.RichTextField()),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('keywords', models.CharField(max_length=150, verbose_name='Keywords')),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('image', models.ImageField(upload_to='blogimage', verbose_name='Image')),
            ],
        ),
    ]
