# Generated by Django 4.0.3 on 2023-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='blog',
            name='month',
            field=models.CharField(default=2, max_length=12, verbose_name='Month'),
            preserve_default=False,
        ),
    ]
