# Generated by Django 4.0.3 on 2023-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_date_blog_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
            ],
        ),
    ]
