# Generated by Django 4.0.3 on 2023-02-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='longtitle',
            field=models.CharField(default=1, max_length=150, verbose_name='Long Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='shorttitle',
            field=models.CharField(default=1, max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
