# Generated by Django 4.0.3 on 2023-02-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_title_blog_longtitle_blog_shorttitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='shorttitle',
            new_name='title',
        ),
    ]
