# Generated by Django 4.0.3 on 2023-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_shorttitle_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.CharField(default=1, max_length=250, verbose_name='Quote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Short Title'),
        ),
    ]
