# Generated by Django 4.0.3 on 2023-02-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_profile_phoneno_profile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PhoneNo',
            field=models.CharField(default=2313123131231312, max_length=12, verbose_name='Phone No'),
            preserve_default=False,
        ),
    ]
