# Generated by Django 4.0.3 on 2023-02-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_profile_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=2, max_length=250, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=2, max_length=250, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.PositiveIntegerField(default=2, verbose_name='Pincode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default=2, max_length=250, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='PhoneNo',
            field=models.PositiveIntegerField(verbose_name='Phone No'),
        ),
    ]
