# Generated by Django 4.0.3 on 2023-02-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_profile_city_alter_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default=1, max_length=250, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default=1, max_length=250, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
