# Generated by Django 4.0.3 on 2023-02-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.AddField(
            model_name='lead',
            name='leadname',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Lead Name'),
        ),
    ]
