# Generated by Django 4.0.3 on 2023-02-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_remove_lead_user_lead_leadname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lead',
            new_name='newleads',
        ),
    ]
