# Generated by Django 4.0.3 on 2023-02-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_newlead_delete_newleads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newlead',
        ),
    ]
