# Generated by Django 4.0.3 on 2023-02-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_delete_newlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='action',
            field=models.BooleanField(default=1, verbose_name='Admission done: '),
            preserve_default=False,
        ),
    ]
