# Generated by Django 4.0.3 on 2023-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_profile_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(default=1, verbose_name='Verified account: '),
            preserve_default=False,
        ),
    ]
