# Generated by Django 4.0.3 on 2023-02-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_profile_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='action',
            field=models.BooleanField(blank=True, null=True, verbose_name='Admission done: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(blank=True, null=True, verbose_name='Verified account: '),
        ),
    ]
