# Generated by Django 4.0.3 on 2023-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_profile_action_alter_profile_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='action',
            field=models.BooleanField(default=False, verbose_name='Admission done: '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(default=False, verbose_name='Verified account: '),
        ),
    ]
