# Generated by Django 4.0.3 on 2023-02-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_profile_action_alter_profile_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referalcode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Referal Code'),
        ),
    ]
