# Generated by Django 4.0.3 on 2023-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100, verbose_name='University Name')),
                ('university_state', models.CharField(max_length=100, verbose_name='State')),
                ('university_city', models.CharField(max_length=100, verbose_name='City')),
                ('university_map_location', models.CharField(max_length=100, verbose_name='University Map Location Address')),
                ('university_rating', models.CharField(max_length=100, verbose_name='Rating')),
                ('university_Discription', models.TextField(blank=True, max_length=500, null=True, verbose_name='Discription')),
                ('university_top_list', models.BooleanField(blank=True, null=True, verbose_name='If the college is TopRated')),
            ],
        ),
    ]
