# Generated by Django 4.0.3 on 2023-02-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university_university_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='college_name',
            field=models.CharField(default=2, max_length=100, verbose_name='College Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='university_map_location',
            field=models.CharField(max_length=10000, verbose_name='University Map Location Address'),
        ),
        migrations.AddField(
            model_name='university',
            name='university_courses',
            field=models.ManyToManyField(to='university.course'),
        ),
    ]
