# Generated by Django 4.0.3 on 2023-02-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_course_university_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_img',
            field=models.ImageField(upload_to='media/university_Image', verbose_name='Image'),
        ),
    ]
