# Generated by Django 4.0.3 on 2023-02-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_course_name_alter_university_university_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(default=2, max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
