# Generated by Django 4.0.3 on 2023-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_university_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='University_category',
            field=models.CharField(choices=[('ENGINEERING', 'ENGINEERING'), ('MANAGEMENT', 'MANAGEMENT'), ('AGRICULTURE', 'AGRICULTURE'), ('ALLIED', 'ALLIED'), ('MBBS', 'MBBS'), ('PARAMEDICAL', 'PARAMEDICAL')], default=2, max_length=250, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
