# Generated by Django 4.0.3 on 2023-02-08 17:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_university_university_category_alter_university_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_Discription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
