# Generated by Django 4.0.3 on 2023-02-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_alter_university_university_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='University_category',
            field=models.CharField(choices=[('ALL', 'ALL'), ('ENGINEERING', 'ENGINEERING'), ('MANAGEMENT', 'MANAGEMENT'), ('AGRICULTURE', 'AGRICULTURE'), ('ALLIED', 'ALLIED'), ('MBBS', 'MBBS'), ('PARAMEDICAL', 'PARAMEDICAL')], max_length=250, verbose_name='Category'),
        ),
    ]
