# Generated by Django 4.0.3 on 2023-02-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_university_search_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_courses_tag',
            field=models.ManyToManyField(to='university.course'),
        ),
        migrations.RemoveField(
            model_name='university',
            name='university_courses',
        ),
        migrations.AddField(
            model_name='university',
            name='university_courses',
            field=models.CharField(default=1, max_length=250, verbose_name='Course'),
            preserve_default=False,
        ),
    ]
