# Generated by Django 4.0.3 on 2023-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_university_university_courses_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='University_category',
            field=models.CharField(choices=[('ALL', 'ALL'), ('ENGINEERING', 'ENGINEERING'), ('MANAGEMENT', 'MANAGEMENT'), ('AGRICULTURE', 'AGRICULTURE'), ('ALLIED', 'ALLIED'), ('MBBS', 'MBBS'), ('PARAMEDICAL', 'PARAMEDICAL'), ('NURSING', 'NURSING')], max_length=250, verbose_name='Category'),
        ),
    ]
